version: 0.2

env:
  parameter-store:
    LOGIN: LOGIN
    HOST: HOST
    Organization: Organization
    Project: Project

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Setting up Maven settings"
      - mkdir -p /root/.m2
      - cp ./settings.xml /root/.m2/settings.xml

      - echo "Getting CodeArtifact token"
      - export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain rexy --domain-owner 326306381458 --region ap-south-1 --query authorizationToken --output text)

      - echo "Installing Maven"
      - wget https://archive.apache.org/dist/maven/maven-3/3.9.4/binaries/apache-maven-3.9.4-bin.tar.gz
      - tar -xzf apache-maven-3.9.4-bin.tar.gz
      - mv apache-maven-3.9.4 /opt/maven
      - ln -sf /opt/maven/bin/mvn /usr/local/bin/mvn
      - mvn -v

  pre_build:
    commands:
      - echo "Installing dependencies"
      - apt-get update
      - apt-get install -y checkstyle

      - echo "Extracting branch name"
      - echo "CODEBUILD_SOURCE_VERSION=$CODEBUILD_SOURCE_VERSION"
      - echo "CODEBUILD_WEBHOOK_HEAD_REF=$CODEBUILD_WEBHOOK_HEAD_REF"
      - export BRANCH_NAME=$(echo "$CODEBUILD_WEBHOOK_HEAD_REF" | sed 's|refs/heads/||')
      - |
        if [ -z "$BRANCH_NAME" ]; then
          BRANCH_NAME=$(echo "$CODEBUILD_SOURCE_VERSION" | sed 's|refs/heads/||')
        fi
      - echo "Resolved branch name: $BRANCH_NAME"

  build:
    commands:
      - echo "Skipping tests for now"
      - mvn clean package -DskipTests

      - echo "Running checkstyle"
      - mvn checkstyle:checkstyle
artifacts:
  files:
    - '**/*'